version: "3.8"

services:
  # ---------------------------------
  # Redis: used for async celery tasks
  # ---------------------------------
  redis:
    image: redis
    command: redis-server --requirepass password
    expose:
      - 6379
  # ---------------------------------
  # Postgres Database
  # ---------------------------------
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=localhost
    ports:
      - "5432:5432"
  # ---------------------------------
  # Client side (Vue.js)
  #  - Built from "client/Dockerfile"
  # ---------------------------------
  # TODO: Load data every time
  client:
    build: "./client"
    environment:
      - DEV_MODE=true
    command: ./run_client.sh
    volumes:
      - .:/code
      - /code/client/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
  # ---------------------------------
  # Server side (Django)
  #  - Built from "server/Dockerfile"
  # ---------------------------------
  server:
    platform: linux/amd64
    build: "./server"
    # For production we will need to set
    # these variables to point to a standalone instance
    #
    # !Note: "opendp_project.settings.cypress_settings" below should never be used for actual deployment.
    #        They include an administrative API endpoint which can "clear" the database.
    #
    environment:
      - DJANGO_SETTINGS_MODULE=opendp_project.settings.cypress_settings
      - VUE_APP_GOOGLE_CLIENT_ID=750757442540-4bg3aulcrm802i8pguo851lq8kikf5ge.apps.googleusercontent.com
      - VUE_APP_ADOBE_PDF_CLIENT_ID=13c79907c6144590b17e8ef044324444
      - SKIP_PDF_CREATION_FOR_TESTS=False
      - SKIP_EMAIL_RELEASE_FOR_TESTS=False
      - VUE_APP_WEBSOCKET_PREFIX=ws://
    env_file:
      - .env
    command: sh -c "python manage.py show_debug_params && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - client
      - db
  # ---------------------------------
  # Celery Task Queue
  # - Used for profiling, other longer
  #   running tasks
  # ---------------------------------
  celery-queue:
    platform: linux/amd64
    build: "./server"
    environment:
      - DJANGO_SETTINGS_MODULE=opendp_project.settings.cypress_settings
    env_file:
      - .env
    command: celery -A opendp_project worker -l info -n worker_dpcreator
    #  command: celery -A opendp_project worker -l INFO
    volumes:
      - .:/code
    ports:
      - "8070:8070"
    depends_on:
      - db
      - redis
      - server

