# Generated by Django 3.1.2 on 2020-11-04 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestTestParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('fileId', models.IntegerField()),
                ('apiSensitiveDataReadToken', models.CharField(blank=True, max_length=255)),
                ('apiGeneralToken', models.CharField(blank=True, max_length=255)),
                ('siteUrl', models.URLField(blank=True, max_length=255)),
                ('filePid', models.CharField(blank=True, max_length=255)),
                ('datasetPid', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredDataverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dataverse_url', models.URLField(help_text='No trailing slash.', unique=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='optional')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
