# Generated by Django 3.1.2 on 2021-02-09 23:11

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestTestParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('fileId', models.IntegerField()),
                ('siteUrl', models.URLField(blank=True, max_length=255)),
                ('use_mock_dv_api', models.BooleanField(default=False, verbose_name='Use Mock Dataverse API')),
                ('apiSensitiveDataReadToken', models.CharField(blank=True, max_length=255)),
                ('apiGeneralToken', models.CharField(blank=True, max_length=255)),
                ('filePid', models.CharField(blank=True, max_length=255)),
                ('datasetPid', models.CharField(blank=True, max_length=255)),
                ('ddi_content', models.TextField(blank=True, help_text='Use XML')),
                ('schema_org_content', models.JSONField(blank=True, null=True)),
                ('user_info', models.JSONField(blank=True, null=True)),
                ('raw_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/ramanprasad/Documents/github-rp/opendp-ux/server/test_setup/user_uploaded_data'), upload_to='mock-files/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Manifest Test Parameter',
                'verbose_name_plural': 'Manifest Test Parameters',
            },
        ),
        migrations.CreateModel(
            name='RegisteredDataverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dataverse_url', models.URLField(help_text='No trailing slash.', unique=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='optional')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
