# Generated by Django 3.1.2 on 2020-11-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesttestparams',
            name='user_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
