# Generated by Django 3.1.2 on 2020-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0002_manifesttestparams_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesttestparams',
            name='use_mock_dv_api',
            field=models.BooleanField(default=False, verbose_name='Use Mock Dataverse API'),
        ),
    ]
