# Generated by Django 3.1.2 on 2021-03-10 18:41

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0002_auto_20210216_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataverseHandoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('siteUrl', models.CharField(max_length=255)),
                ('fileId', models.CharField(max_length=255)),
                ('datasetPid', models.CharField(help_text='Dataset DOI', max_length=255)),
                ('filePid', models.CharField(blank=True, help_text='File DOI', max_length=255)),
                ('apiGeneralToken', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('apiSensitiveDataReadToken', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
            ],
            options={
                'verbose_name': 'Dataverse Handoff Parameter',
                'verbose_name_plural': 'Dataverse Handoff Parameters',
            },
        ),
    ]
