# Generated by Django 3.1.8 on 2021-07-15 02:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0002_auto_20210503_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesttestparams',
            name='raw_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/ramanprasad/Documents/github-rp/opendp-ux/server/test_setup/user_uploaded_data'), upload_to='mock-files/%Y/%m/%d/'),
        ),
    ]
