# Generated by Django 3.1.13 on 2021-11-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0003_auto_20211115_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifesttestparams',
            name='ddi_content',
        ),
    ]
