# Generated by Django 3.1.6 on 2021-03-31 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0004_auto_20210318_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataversehandoff',
            name='dv_installation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataverses.registereddataverse'),
            preserve_default=False,
        ),
    ]
