# Generated by Django 3.1.6 on 2021-04-03 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0005_dataversehandoff_dv_installation'),
        ('dataverses', '0005_auto_20210331_1743'),
    ]

    operations = [
    ]
