# Generated by Django 3.1.6 on 2021-03-30 14:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0005_auto_20210329_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesttestparams',
            name='raw_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/server/test_setup/user_uploaded_data'), upload_to='mock-files/%Y/%m/%d/'),
        ),
    ]
