# Generated by Django 3.1.2 on 2021-04-28 13:03

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0006_merge_20210403_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataversehandoff',
            name='apiSensitiveDataReadToken',
        ),
        migrations.RemoveField(
            model_name='manifesttestparams',
            name='apiSensitiveDataReadToken',
        ),
        migrations.AlterField(
            model_name='dataversehandoff',
            name='dv_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataverses.registereddataverse'),
        ),
        migrations.AlterField(
            model_name='manifesttestparams',
            name='raw_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/ramanprasad/Documents/github-rp/opendp-ux/server/test_setup/user_uploaded_data'), upload_to='mock-files/%Y/%m/%d/'),
        ),
    ]
