# Generated by Django 3.1.2 on 2021-04-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0007_auto_20210428_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataversehandoff',
            old_name='siteUrl',
            new_name='site_url',
        ),
        migrations.RenameField(
            model_name='manifesttestparams',
            old_name='siteUrl',
            new_name='site_url',
        ),
    ]
