# Generated by Django 3.1.2 on 2021-04-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0008_auto_20210428_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataversehandoff',
            name='site_url',
        ),
    ]
