# Generated by Django 3.1.2 on 2020-10-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        ('user', '0001_initial'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.session'),
        ),
        migrations.AddField(
            model_name='dprelease',
            name='dataset_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.basedatasetinfo'),
        ),
        migrations.AddField(
            model_name='dprelease',
            name='group',
            field=models.ManyToManyField(to='user.Group'),
        ),
        migrations.AddField(
            model_name='dprelease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dataverseuser'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dataverseuser'),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='computations',
            field=models.ManyToManyField(to='analysis.Computation'),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.dataset'),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dataverseuser'),
        ),
    ]
