# Generated by Django 3.1.2 on 2021-04-28 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataset', '0001_initial'),
        ('analysis', '0002_auto_20210428_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisplan',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataset.datasetinfo'),
        ),
    ]
