# Generated by Django 3.2.18 on 2023-06-21 11:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseinfo',
            name='dp_release_json_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/server/test_setup/public_release_files'), upload_to='release-files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='dp_release_pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/server/test_setup/public_release_files'), upload_to='release-files/%Y/%m/%d/'),
        ),
    ]
