# Generated by Django 3.1.12 on 2021-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210728_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisplan',
            name='custom_variables',
        ),
        migrations.RemoveField(
            model_name='analysisplan',
            name='variable_categories',
        ),
        migrations.RemoveField(
            model_name='analysisplan',
            name='variable_ranges',
        ),
        migrations.RemoveField(
            model_name='depositorsetupinfo',
            name='variable_categories',
        ),
        migrations.RemoveField(
            model_name='depositorsetupinfo',
            name='variable_ranges',
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='variable_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositorsetupinfo',
            name='variable_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
