# Generated by Django 4.0 on 2023-07-17 16:54

import django.core.files.storage
from django.db import migrations, models
import opendp_apps.utils.extra_validators


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_releaseinfo_dp_release_json_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisplan',
            name='delta',
            field=models.FloatField(blank=True, default=0.0, help_text='Used for OpenDP operations, starts as the "default_delta" value but may be overridden by the user.', null=True, validators=[opendp_apps.utils.extra_validators.validate_not_negative]),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the analysis plan'),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='epsilon',
            field=models.FloatField(blank=True, help_text='Used for OpenDP operations, starts as the "default_epsilon" value but may be overridden by the user.', null=True, validators=[opendp_apps.utils.extra_validators.validate_epsilon_or_none]),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='The date the analysis plan expires', null=True),
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='wizard_step',
            field=models.CharField(default='step_100', help_text='Used by the UI to track the wizard step', max_length=128),
        ),
        migrations.AlterField(
            model_name='analysisplan',
            name='dp_statistics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisplan',
            name='name',
            field=models.CharField(help_text='Name of the analysis plan', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysisplan',
            name='user_step',
            field=models.CharField(choices=[('step_100', 'Step 0: Initialized'), ('step_700', 'Step 7: Variables Confirmed'), ('step_800', 'Step 8: Statistics Created'), ('step_900', 'Step 9: Statistics Submitted'), ('step_1000', 'Step 10: Release Complete'), ('step_1100', 'Step 11: Dataverse Release Deposited'), ('step_1200', 'Step 12: Process Complete'), ('error_9500', 'Error 5: Release Creation Failed'), ('error_9600', 'Error 6: Release Deposit Failed')], default='step_100', max_length=128),
        ),
        migrations.AlterField(
            model_name='analysisplan',
            name='variable_info',
            field=models.JSONField(blank=True, help_text='Default value taken from DepositorSetupInfo', null=True),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='dp_release_json_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/ramanprasad/Documents/github-rp/dpcreator/server/test_setup/public_release_files'), upload_to='release-files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='dp_release_pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/ramanprasad/Documents/github-rp/dpcreator/server/test_setup/public_release_files'), upload_to='release-files/%Y/%m/%d/'),
        ),
    ]
