# Generated by Django 3.1.8 on 2021-05-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20210503_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='user_step',
            field=models.CharField(choices=[('step_100', 'Step 1: Uploaded'), ('step_200', 'Step 2: Validated'), ('step_300', 'Step 3: Variables Confirmed'), ('step_400', 'Step 4: Epsilon Set'), ('step_500', 'Step 5: Statistics Created'), ('step_600', 'Step 6: Statistics Submitted'), ('step_700', 'Step 7: Release Complete'), ('step_800', 'Step 8: Dataverse Release Deposited'), ('step_900', 'Step 9: Process Complete'), ('error_9100', 'Error 1: Validation Failed'), ('error_9200', 'Error 2: Dataverse Download Failed'), ('error_9300', 'Error 3: Profiling Failed'), ('error_9400', 'Error 4: Create Release Failed')], max_length=128),
        ),
    ]
