# Generated by Django 3.1.12 on 2021-08-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20210729_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisplan',
            name='user_step',
            field=models.CharField(choices=[('step_700', 'Step 7: Variables Confirmed'), ('step_800', 'Step 8: Statistics Created'), ('step_900', 'Step 9: Statistics Submitted'), ('step_1000', 'Step 10: Release Complete'), ('step_1100', 'Step 11: Dataverse Release Deposited'), ('step_1200', 'Step 12: Process Complete'), ('error_9500', 'Error 5: Release Creation Failed'), ('error_9600', 'Error 6: Release Deposit Failed')], max_length=128),
        ),
    ]
