# Generated by Django 4.0 on 2023-07-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysisplan_delta_analysisplan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisplan',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the analysis plan', null=True),
        ),
    ]
