# Generated by Django 3.1.8 on 2021-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20210505_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisplan',
            name='user_step',
            field=models.CharField(choices=[('step_500', 'Step 5: Variables Confirmed'), ('step_600', 'Step 6: Statistics Created'), ('step_700', 'Step 7: Statistics Submitted'), ('step_800', 'Step 8: Release Complete'), ('step_900', 'Step 9: Dataverse Release Deposited'), ('step_1000', 'Step 10: Process Complete'), ('error_9500', 'Error 5: Release Creation Failed'), ('error_9600', 'Error 6: Release Deposit Failed')], max_length=128),
        ),
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='user_step',
            field=models.CharField(choices=[('step_100', 'Step 1: Uploaded'), ('step_200', 'Step 2: Validated'), ('step_300', 'Step 3: Profiling Processing'), ('step_400', 'Step 4: Profiling Complete'), ('step_500', 'Step 5: Variable Defaults Confirmed'), ('step_600', 'Step 6: Epsilon Set'), ('error_9100', 'Error 1: Validation Failed'), ('error_9200', 'Error 2: Dataverse Download Failed'), ('error_9300', 'Error 3: Profiling Failed'), ('error_9400', 'Error 4: Create Release Failed')], max_length=128),
        ),
    ]
