# Generated by Django 3.1.12 on 2021-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20210818_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositorsetupinfo',
            name='default_epsilon',
            field=models.FloatField(blank=True, help_text='Default based on answers to epsilon_questions.', null=True),
        ),
        migrations.AddField(
            model_name='depositorsetupinfo',
            name='epsilon_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='epsilon',
            field=models.FloatField(blank=True, help_text='Used for OpenDP operations, starts as the "default_epsilon" value but may be overridden by the user.', null=True),
        ),
    ]
