# Generated by Django 4.0 on 2023-07-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_analysisplan_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisplan',
            options={'ordering': ['dataset', 'name', '-created']},
        ),
    ]
