# Generated by Django 3.1.12 on 2021-09-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20210901_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositorsetupinfo',
            name='confidence_interval',
            field=models.FloatField(choices=[(0.05, '95% CI'), (0.01, '99% CI')], default=0.05, help_text='Used for OpenDP operations, starts as the "default_delta" value but may be overridden by the user.'),
        ),
        migrations.AddField(
            model_name='depositorsetupinfo',
            name='default_delta',
            field=models.FloatField(blank=True, default=0.0, help_text='Default based on answers to epsilon_questions.', null=True),
        ),
        migrations.AddField(
            model_name='depositorsetupinfo',
            name='delta',
            field=models.FloatField(blank=True, default=0.0, help_text='Used for OpenDP operations, starts as the "default_delta" value but may be overridden by the user.', null=True),
        ),
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='auto-populated on save'),
        ),
    ]
