# Generated by Django 3.1.8 on 2021-05-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20210505_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositorsetupinfo',
            options={'ordering': ('created',), 'verbose_name': 'Depositor Setup Data', 'verbose_name_plural': 'Depositor Setup Data'},
        ),
        migrations.RemoveField(
            model_name='depositorsetupinfo',
            name='dataset',
        ),
    ]
