# Generated by Django 3.1.12 on 2021-09-02 01:21

from django.db import migrations, models
import opendp_apps.utils.extra_validators


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20210902_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='default_delta',
            field=models.FloatField(blank=True, default=0.0, help_text='Default based on answers to epsilon_questions.', null=True, validators=[opendp_apps.utils.extra_validators.validate_not_negative]),
        ),
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='default_epsilon',
            field=models.FloatField(blank=True, help_text='Default based on answers to epsilon_questions.', null=True, validators=[opendp_apps.utils.extra_validators.validate_not_negative_or_none]),
        ),
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='delta',
            field=models.FloatField(blank=True, default=0.0, help_text='Used for OpenDP operations, starts as the "default_delta" value but may be overridden by the user.', null=True, validators=[opendp_apps.utils.extra_validators.validate_not_negative]),
        ),
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='epsilon',
            field=models.FloatField(blank=True, help_text='Used for OpenDP operations, starts as the "default_epsilon" value but may be overridden by the user.', null=True, validators=[opendp_apps.utils.extra_validators.validate_not_negative_or_none]),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='epsilon_used',
            field=models.FloatField(validators=[opendp_apps.utils.extra_validators.validate_not_negative]),
        ),
    ]
