# Generated by Django 3.1.8 on 2021-05-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20210505_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositorsetupinfo',
            options={'ordering': ('dataversefileinfo', '-created'), 'verbose_name': 'Depositor Setup Data', 'verbose_name_plural': 'Depositor Setup Data'},
        ),
    ]
