# Generated by Django 3.1.12 on 2021-09-08 01:52

from django.db import migrations, models
import opendp_apps.utils.extra_validators


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20210902_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='default_epsilon',
            field=models.FloatField(blank=True, help_text='Default based on answers to epsilon_questions.', null=True, validators=[opendp_apps.utils.extra_validators.validate_epsilon_or_none]),
        ),
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='epsilon',
            field=models.FloatField(blank=True, help_text='Used for OpenDP operations, starts as the "default_epsilon" value but may be overridden by the user.', null=True, validators=[opendp_apps.utils.extra_validators.validate_epsilon_or_none]),
        ),
    ]
