# Generated by Django 3.1.8 on 2021-05-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20210506_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='user_step',
            field=models.CharField(choices=[('step_100', 'Step 1: Uploaded'), ('step_200', 'Step 2: Validated'), ('step_300', 'Step 3: Profiling Processing'), ('step_400', 'Step 4: Profiling Complete'), ('step_500', 'Step 5: Variable Defaults Confirmed'), ('step_600', 'Step 6: Epsilon Set'), ('error_9100', 'Error 1: Validation Failed'), ('error_9200', 'Error 2: Dataverse Download Failed'), ('error_9300', 'Error 3: Profiling Failed'), ('error_9400', 'Error 4: Create Release Failed')], default='step_100', max_length=128),
        ),
    ]
