# Generated by Django 3.1.12 on 2021-09-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20210908_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositorsetupinfo',
            options={'ordering': ('-created',), 'verbose_name': 'Depositor Setup Data', 'verbose_name_plural': 'Depositor Setup Data'},
        ),
    ]
