# Generated by Django 3.1.12 on 2021-09-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20210913_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseinfo',
            name='analysis_plan',
        ),
        migrations.AddField(
            model_name='analysisplan',
            name='release_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analysis.releaseinfo'),
        ),
    ]
