# Generated by Django 3.1.12 on 2021-09-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20210917_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseinfo',
            name='dp_release_json',
            field=models.FileField(blank=True, null=True, storage='/Users/ramanprasad/Documents/github-rp/dpcreator/server/test_setup/public_release_files', upload_to='release-files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='releaseinfo',
            name='dp_release_pdf',
            field=models.FileField(blank=True, null=True, storage='/Users/ramanprasad/Documents/github-rp/dpcreator/server/test_setup/public_release_files', upload_to='release-fils/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='depositorsetupinfo',
            name='confidence_interval',
            field=models.FloatField(choices=[(0.1, '90% CI'), (0.05, '95% CI'), (0.01, '99% CI')], default=0.05, help_text='Used for OpenDP operations, starts as the "default_delta" value but may be overridden by the user.'),
        ),
    ]
