# Generated by Django 3.1.8 on 2021-05-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_depositorsetupinfo_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositorsetupinfo',
            name='creator',
        ),
    ]
