# Generated by Django 3.1.12 on 2021-09-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_auto_20210919_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releaseinfo',
            old_name='dp_release_json',
            new_name='dp_release_json_file',
        ),
        migrations.RemoveField(
            model_name='releaseinfo',
            name='dp_release_pdf',
        ),
        migrations.AddField(
            model_name='releaseinfo',
            name='dp_release_pdf_file',
            field=models.FileField(blank=True, null=True, storage='/Users/ramanprasad/Documents/github-rp/dpcreator/server/test_setup/public_release_files', upload_to='release-files/%Y/%m/%d/'),
        ),
    ]
