# Generated by Django 3.1.8 on 2021-05-24 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0012_remove_depositorsetupinfo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositorsetupinfo',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.opendpuser'),
            preserve_default=False,
        ),
    ]
