# Generated by Django 3.1.13 on 2021-10-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20210919_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositorsetupinfo',
            name='confidence_interval',
        ),
        migrations.AddField(
            model_name='depositorsetupinfo',
            name='confidence_level',
            field=models.FloatField(choices=[(0.9, '90% CL'), (0.95, '95% CL'), (0.99, '99% CL')], default=0.95, help_text='Used for OpenDP operations, starts as the "default_delta" value but may be overridden by the user.'),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='dp_release_json_file',
            field=models.FileField(blank=True, null=True, upload_to='release-files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='dp_release_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='release-files/%Y/%m/%d/'),
        ),
    ]
