# Generated by Django 3.1.13 on 2021-11-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20211020_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseinfo',
            name='dataverse_deposit_complete',
            field=models.BooleanField(default=False, help_text='Only applies to Dataverse datasets'),
        ),
    ]
