# Generated by Django 3.1.13 on 2021-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_releaseinfo_dataverse_deposit_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releaseinfo',
            old_name='dataverse_deposit_complete',
            new_name='dv_json_deposit_complete',
        ),
        migrations.AddField(
            model_name='releaseinfo',
            name='dv_pdf_deposit_complete',
            field=models.BooleanField(default=False, help_text='Only applies to Dataverse datasets'),
        ),
    ]
