# Generated by Django 3.1.13 on 2021-11-16 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20211115_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisplan',
            name='release_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.releaseinfo'),
        ),
        migrations.CreateModel(
            name='AuxiliaryFileDepositRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, help_text='auto-filled on save', max_length=255)),
                ('deposit_success', models.BooleanField(default=False)),
                ('dv_auxiliary_type', models.CharField(choices=[('dpJSON', 'dpJSON'), ('dpPDF', 'dpPDF')], max_length=100)),
                ('dv_auxiliary_version', models.CharField(default='v1', help_text='e.g. "v1", "v2", etc', max_length=50)),
                ('http_status_code', models.IntegerField(default=-1, help_text='HTTP code')),
                ('http_resp_text', models.TextField(blank=True)),
                ('http_resp_json', models.JSONField(blank=True, null=True)),
                ('user_msg', models.TextField(blank=True)),
                ('dv_download_url', models.URLField(blank=True)),
                ('release_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.releaseinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
