# Generated by Django 3.1.13 on 2021-11-30 02:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_releaseinfo_dataverse_deposit_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseinfo',
            name='dp_release_json_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/server/test_setup/public_release_files'), upload_to='release-files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='releaseinfo',
            name='dp_release_pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/code/server/test_setup/public_release_files'), upload_to='release-files/%Y/%m/%d/'),
        ),
    ]
