# Generated by Django 3.1.13 on 2022-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_auto_20211130_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliaryfiledepositrecord',
            name='dv_auxiliary_type',
            field=models.CharField(choices=[('dpJson', 'dpJson'), ('dpPDF', 'dpPDF')], max_length=100),
        ),
    ]
