# Generated by Django 3.1.13 on 2022-03-20 23:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_auto_20220214_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseEmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('success', models.BooleanField(help_text='Did the mail go through?')),
                ('subject', models.CharField(max_length=255)),
                ('to_email', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('email_content', models.TextField(blank=True)),
                ('pdf_attached', models.BooleanField()),
                ('json_attached', models.BooleanField()),
                ('note', models.TextField(blank=True, help_text='Populated if mail not sent successfully')),
                ('release_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.releaseinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
