# Generated by Django 3.1.2 on 2020-10-21 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisPlan',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('user_step', models.CharField(choices=[('step_010', 'Step 10: Terms of Access'), ('step_020', 'Step 20: Custom Variables'), ('step_030', 'Step 30: Confirm Variable Types'), ('step_100', 'Step 100: Analysis ready!')], max_length=128)),
                ('variable_ranges', models.JSONField(null=True)),
                ('variable_categories', models.JSONField(null=True)),
                ('custom_variables', models.JSONField(null=True)),
                ('dp_statistics', models.JSONField(null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.datasetinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseInfo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epsilon_used', models.FloatField()),
                ('dp_release', models.JSONField()),
                ('analysis_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyses.analysisplan')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.datasetinfo')),
            ],
            options={
                'verbose_name': 'Release Information',
                'verbose_name_plural': 'Release Information',
                'ordering': ('dataset', '-created'),
            },
        ),
        migrations.CreateModel(
            name='DepositorSetupInfo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('user_step', models.CharField(choices=[('step_10', 'Step 10: Terms of Access'), ('step_20', 'Step 20: Upload'), ('step_30', 'Step 30: Dataset Type')], max_length=128)),
                ('epsilon', models.FloatField(blank=True, null=True)),
                ('dataset_questions', models.JSONField(null=True)),
                ('variable_ranges', models.JSONField(null=True)),
                ('variable_categories', models.JSONField(null=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='datasets.datasetinfo')),
            ],
            options={
                'verbose_name': 'Depositor Setup Data',
                'verbose_name_plural': 'Depositor Setup Data',
                'ordering': ('dataset', '-created'),
            },
        ),
    ]
