# Generated by Django 3.1.2 on 2020-10-23 17:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opendpuser',
            options={'base_manager_name': 'non_polymorphic'},
        ),
        migrations.AlterModelManagers(
            name='opendpuser',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='opendpuser',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_user.opendpuser_set+', to='contenttypes.contenttype'),
        ),
    ]
