# Generated by Django 3.1.2 on 2021-02-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataverseuser',
            options={'verbose_name': 'Dataverse User'},
        ),
        migrations.AlterModelOptions(
            name='opendpuser',
            options={'verbose_name': 'OpenDP User'},
        ),
    ]
