# Generated by Django 3.1.13 on 2021-11-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataverseuser',
            name='dv_sensitive_token',
        ),
        migrations.RemoveField(
            model_name='dataverseuser',
            name='dv_token_update',
        ),
    ]
