# Generated by Django 3.1.13 on 2022-03-04 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211113_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendpuser',
            name='handoff_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Temporary storage of a DataverseHandoff.object_id when arriving from Dataverse.', null=True),
        ),
    ]
