# Generated by Django 3.1.2 on 2020-10-23 17:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201023_1754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='opendpuser',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
    ]
