# Generated by Django 3.1.6 on 2021-04-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverses', '0006_merge_20210403_0229'),
        ('user', '0003_auto_20210331_1750'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataverseuser',
            unique_together={('user', 'dv_installation')},
        ),
    ]
