# Generated by Django 3.1.2 on 2020-10-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201023_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opendpuser',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='opendpuser',
            managers=[
            ],
        ),
    ]
