# Generated by Django 3.1.2 on 2020-10-23 18:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201023_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opendpuser',
            options={'base_manager_name': 'manager'},
        ),
        migrations.AlterModelManagers(
            name='opendpuser',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
