# Generated by Django 3.1.2 on 2020-10-29 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201023_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataverseUser',
            fields=[
                ('opendpuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.opendpuser')),
                ('installation', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user.opendpuser',),
            managers=[
                ('manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('DE', 'Depositor'), ('AN', 'Analyst')], max_length=2)),
                ('status', models.IntegerField(choices=[(1, 'Preparation'), (2, 'Statistic Creation'), (3, 'Awaiting Execution Engine'), (4, 'Error'), (5, 'Dataverse Deposit Complete')], default=1)),
                ('terms_of_use_accepted', models.BooleanField(default=False)),
                ('request_parameters', models.JSONField()),
                ('token_parameters_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
