# Generated by Django 3.1.2 on 2020-11-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201104_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opendpuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
