# Generated by Django 3.1.2 on 2020-10-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_dataverseuser_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataverseuser',
            name='installation',
        ),
    ]
