# Generated by Django 3.2.18 on 2023-04-27 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='For internal reference, not displayed', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Set to True to display banner')),
                ('type', models.CharField(choices=[('INFO', 'Informational Banner'), ('WARN', 'Warning Banner')], help_text='Used by the UI to determine display formatting', max_length=128)),
                ('sort_order', models.IntegerField(default=1, help_text='Relative sort order if there is more than 1 active banner.')),
                ('content', models.TextField(help_text='Banner content. May contain basic HTMl tags: links, boldface, etc.')),
                ('is_timed_message', models.BooleanField(default=False, help_text='Optional. If True, use "active" as well as both "view_start_time"/"view_stop_time" settings to determine banner display.')),
                ('view_start_time', models.DateTimeField(blank=True, help_text='Optional. Used in conjunction with "is_timed_message" and "view_stop_time"', null=True)),
                ('view_stop_time', models.DateTimeField(blank=True, help_text='Optional. Used in conjunction with "is_timed_message" and "view_start_time"', null=True)),
                ('editor', models.ForeignKey(blank=True, help_text='auto-filled on save', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner Message',
                'verbose_name_plural': 'Banner Messages',
                'db_table': 'banner_messages',
                'ordering': ('active', 'sort_order', '-created'),
            },
        ),
    ]
