# Generated by Django 3.1.2 on 2020-10-07 18:25

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataverseUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('DE', 'Depositor'), ('AN', 'Analyst')], max_length=2)),
                ('status', models.IntegerField(choices=[(1, 'Preparation'), (2, 'Statistic Creation'), (3, 'Awaiting Execution Engine'), (4, 'Error'), (5, 'Dataverse Deposit Complete')], default=1)),
                ('terms_of_use_accepted', models.BooleanField(default=False)),
                ('request_parameters', models.JSONField()),
                ('token_parameters_key', models.TextField()),
                ('dataverse_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataverse.dataversefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dataverseuser')),
            ],
        ),
    ]
