# Generated by Django 4.2 on 2023-09-06 17:46

from django.db import migrations, models
import opendp_apps.release_schemas.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseInfoSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version', models.CharField(help_text='Semantic version. Example: 1.4.2', max_length=50, unique=True, validators=[opendp_apps.release_schemas.validators.validate_semantic_version_number], verbose_name='Version number')),
                ('title', models.CharField(help_text='(auto-generated) Name of the schema. Include the "Version number" in the name.', max_length=128, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('schema', models.JSONField(help_text='JSON schema', validators=[opendp_apps.release_schemas.validators.validate_json_schema])),
                ('schema_link', models.URLField(blank=True, help_text='(auto-filled) Link to the schema, using the keyword "$schema"')),
                ('id_link', models.URLField(blank=True, help_text='(auto-filled) Link to the "id", trying the keywords "id" and "$id"')),
                ('description', models.TextField(blank=True)),
                ('sortable_version', models.CharField(help_text='Auto-populated. Sortable version of the schema.', max_length=50)),
            ],
            options={
                'ordering': ['-sortable_version'],
            },
        ),
    ]
