# Generated by Django 4.2 on 2023-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseinfoschema',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the schema'),
        ),
        migrations.AlterField(
            model_name='releaseinfoschema',
            name='id_link',
            field=models.URLField(blank=True, help_text='(auto-filled) Value of the schema\'s "$id" property, if available'),
        ),
        migrations.AlterField(
            model_name='releaseinfoschema',
            name='schema_link',
            field=models.URLField(blank=True, help_text='(auto-filled) Value of the schema\'s "$schema" property, if available'),
        ),
        migrations.AlterField(
            model_name='releaseinfoschema',
            name='sortable_version',
            field=models.CharField(help_text='(auto-filled) Sortable version number of the schema.', max_length=50),
        ),
        migrations.AlterField(
            model_name='releaseinfoschema',
            name='title',
            field=models.CharField(blank=True, help_text='(auto-generated) Value of the schema\'s "title" property.', max_length=128),
        ),
    ]
