# Generated by Django 4.0 on 2023-07-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terms_of_access', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofaccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.opendpuser'),
        ),
    ]
