# Generated by Django 3.1.2 on 2020-10-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_of_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsofaccess',
            options={'ordering': ('active', 'name'), 'verbose_name': 'Terms of Access', 'verbose_name_plural': 'Terms of Access'},
        ),
        migrations.AddField(
            model_name='termsofaccess',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
