# Generated by Django 3.1.12 on 2021-07-21 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('terms_of_access', '0002_termsofaccesslog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsofaccesslog',
            name='dataset_info',
        ),
        migrations.AddField(
            model_name='termsofaccess',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
