name: dpcreator-integration-tests
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the client static files
        run: docker-compose -f docker-compose-ci-step1.yml up
      - name: Build server and test
        run: docker-compose -f  docker-compose-ci-step2.yml up --exit-code-from cypress
      - name: Archive Cypress test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: client/cypress/videos
          retention-days: 3
