# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: server-tests-python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        cd server
        pip install -r requirements/dev.txt
        cd ../
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd server
        python manage.py test
        # python manage.py test opendp_apps.analysis opendp_apps.communication opendp_apps.content_pages
        # python manage.py test opendp_apps.dataset
        # python manage.py test opendp_apps.dataverses opendp_apps.model_helpers
        # python manage.py test opendp_apps.profiler opendp_apps.terms_of_access opendp_apps.user
